CREATE DATABASE IF NOT EXISTS BITS;
USE BITS;
CREATE TABLE Student(
    S_ID INT NOT NULL,
    NAME CHAR(20) NOT NULL,
    YEAR INT NOT NULL,
    PRIMARY KEY (S_ID)
);
CREATE TABLE Hostel(
    H_ID INT NOT NULL,
    H_NAME CHAR(20) NOT NULL,
    CAPACITY INT NOT NULL,
    STATUS BOOLEAN,
    PRIMARY KEY (H_NAME)
);
CREATE TABLE Rooms(
    H_NAME CHAR(20) NOT NULL,
    WING_NUMBER INT NOT NULL,
    ROOM_NUMBER INT NOT NULL,
    STATUS_OF_OCCUPANCY BOOLEAN,
    PRIMARY KEY (H_NAME,ROOM_NUMBER)
);
INSERT INTO Student VALUES
    (1, 'Rishabh Sahni', 2),
    (2, 'Sanshrav Arora', 2),
    (3, 'Aarjav Jain', 3),
    (4, 'Sidharth Gupta', 4),
    (5, 'Dhruv Shah', 5),
    (6, 'Rudraksh Patel', 1),
    (7, 'Kshitish Kumar', 1),
    (8, 'Kahsvi Gupta', 1),
    (9, 'Namish Bansal', 1),
    (10, 'Kashish Khanna', 1),
    (11, 'Gautamn Yadav', 1),
    (12, 'Aakash Bhagat', 1),
    (13, 'Lakshay Bansal', 1),
    (14, 'Pooja Mehta', 1),
    (15, 'Hitansh Tanna', 1),
    (16, 'Saksham Sandhu', 1),
    (17, 'Mayank Garg', 1),
    (18, 'Harshit Mehendiratta', 5),
    (19, 'Ishika Dhiman', 2),
    (20, 'Aryan Gupta', 2),
    (21, 'Sagar Bhan', 2),
    (22, 'Aryan Bansal', 2),
    (23, 'Garvit Singhal', 2),
    (24, 'Aditya Verma', 2),
    (25, 'Ayush Sharma', 2),
    (26, 'Sanidhya Vijaivargia', 2),
    (27, 'Patha Adithsai', 2),
    (28, 'Vikrant Rewal', 2),
    (29, 'Lalit Pachori', 3),
    (30, 'Ayush Gupta', 3),
    (31, 'Prajwal Gupta', 3),
    (32, 'Aditya Vinayak', 3),
    (33, 'Ritwik Tiwari', 3),
    (34, 'Aditya Sharma', 3),
    (35, 'Ambuj Saxena', 3),
    (36, 'Rishabh Dhandharia', 3),
    (37, 'Parth Sharma', 3),
    (38, 'Amit Tripathi', 3),
    (39, 'Parth Rusagi', 3),
    (40, 'Aditya Khetan', 4),
    (41, 'Ritvik Channa', 4),
    (42, 'Hemant Dubey', 4),
    (43, 'taniishq SAINI',4),
    (44, 'Manan ARORA',4),
    (45 ,'JAY Goyal',4),
    (46, 'TIKESH VAISHNAV',4),
    (47, 'AARYA Garg',4),
    (48, 'ABHAY NARENDRAN',4),
    (49, 'ARCHi JAIN',4),
    (50, 'Yugal Joshi',4),
    (51, 'PURU AGARWAL',5),
    (52, 'SIDDHANT SINHA',5),
    (53,'SHAURYa BHARDWAJ',5),
    (54, 'MRIDUL VIRALKA',5),
    (55, 'AZHAAN ANVER',5),
    (56,'MANAV Duggal',5),
    (57,'CHINMAY Ananad',5),
    (58, 'PARIVESH BAJPAI',5),
    (59, 'Arham SINGH',5),
    (60, 'Arham Jain',5),
    (61, 'Aarya Thipse',5),
    (62, 'Avyakt Garg',5),
    (63, 'shiwangi PACHORI',1),
    (64, 'AYUSH GUPTA',3),
    (65, 'Aryan GUPTA',3),
    (66, 'VINAYAK',3),
    (67,'RITWIK TIWARI',3),
    (68, 'ADITYA SHARMA',3),
    (69, 'AMBUJ SAXENA',3),
    (70,'RISHABH DHANDHARIA',3),
    (71,'PARTH SHARMA',3),
    (72, 'Amit TRIPATHI',3),
    (73, 'Parth RUSAGI',3),
    (74, 'ADITYA KHETAN',4),
    (75, 'RITvik CHAnnA',4),
    (76, 'Hemant DUBEY',4),
    (77, 'taniishq SAINI',4),
    (78, 'Manan ARORA',4),
    (79 ,'JAY Goyal',4),
    (80, 'TIKESH VAISHNAV',4),
    (81, 'AARYA Garg',4),
    (82, 'ABHAY NARENDRAN',4),
    (83, 'ARCHi JAIN',4),
    (84, 'Yugal Joshi',4),
    (85, 'PURU AGARWAL',5),
    (86, 'SIDDHANT SINHA',5),
    (87,'SHAURYa BHARDWAJ',5),
    (88, 'MRIDUL VIRALKA',5),
    (89, 'AZHAAN ANVER',5),
    (90,'MANAV Duggal',5),
    (91,'CHINMAY Ananad',5),
    (92, 'PARIVESH BAJPAI',5),
    (93, 'Arham SINGH',5),
    (94, 'Arham Jain',5),
    (95, 'Aarya Thipse',5),
    (96, 'Avyakt Garg',5);
Insert into Hostel values
    (1 ,'Vyas' , 60,FALSE),
    (2, 'Ram' , 60,FALSE),
    (3, 'Gandhi' , 60,FALSE),
    (4, 'Krishna' , 60,FALSE),
    (5, 'Budh' , 60,FALSE);
insert into Rooms values
    ('Vyas',1 , 1 , False ),
    ('Vyas',1 , 2 , False ),
    ('Vyas',1 , 3 , False ),
    ('Vyas',2 , 4 , False ),
    ('Vyas',2, 5 , False ),
    ('Vyas',2 , 6 , False ),
    ('Vyas' ,3, 7 , False ),
    ('Vyas',3 , 8 , False ),
    ('Vyas',3 , 9 , False ),
    ('Vyas',4 , 10 , False ),
    ('Vyas',4 , 11, False ),
    ('Vyas',4 , 12 , False ),
    ('Vyas',5 , 13 , False ),
    ('Vyas',5 , 14 , False ),
    ('Vyas',5 , 15 , False ),
    ('Vyas',6 , 16 , False ),
    ('Vyas',6 , 17 , False ),
    ('Vyas',6 , 18 , False ),
    ('Ram' ,1, 1 , False ),
    ('Ram' ,1, 2 , False ),
    ('Ram' ,1, 3 , False ),
    ('Ram' ,2, 4 , False ),
    ('Ram' ,2, 5 , False ),
    ('Ram' ,2, 6 , False ),
    ('Ram' ,3, 7 , False ),
    ('Ram',3, 8 , False ),
    ('Ram',3, 9 , False ),
    ('Ram',4, 10 , False ),
    ('Ram' ,4, 11, False ),
    ('Ram' ,4, 12 , False ),
    ('Gandhi'  ,1, 1 , False ),
    ('Gandhi'  ,1, 2 , False ),
    ('Gandhi'  ,1, 3 , False ),
    ('Gandhi' ,2, 4 , False ),
    ('Gandhi'  , 2,5 , False ),
    ('Gandhi'  ,2, 6 , False ),
    ('Gandhi'  ,3, 7 , False ),
    ('Gandhi'  ,3, 8 , False ),
    ('Gandhi'  ,3, 9 , False ),
    ('Gandhi'  ,4, 10 , False ),
    ('Gandhi'  ,4, 11, False ),
    ('Gandhi'  ,4, 12 , False ),
    ('Gandhi'  ,5, 13 , False ),
    ('Gandhi'  ,5, 14 , False ),
    ('Gandhi'  ,5, 15 , False ),
    ('Gandhi'  ,6, 16 , False ),
    ('Gandhi'  ,6, 17 , False ),
    ('Gandhi'  ,6, 18 , False ),
    ('Krishna' ,1, 1 , False ),
    ('Krishna' ,1, 2 , False ),
    ('Krishna' ,1, 3 , False ),
    ('Krishna' ,2, 4 , False ),
    ('Krishna' ,2, 5 , False ),
    ('Krishna' ,2, 6 , False ),
    ('Krishna' ,3, 7 , False ),
    ('Krishna' ,3, 8 , False ),
    ('Krishna' ,3, 9 , False ),
    ('Krishna' ,4, 10 , False ),
    ('Krishna' ,4, 11, False ),
    ('Krishna' ,4, 12 , False ),
    ('Krishna' ,5, 13 , False ),
    ('Krishna' ,5, 14 , False ),
    ('Krishna' ,5, 15 , False ),
    ('Budh' ,1, 1 , False ),
    ('Budh' ,1, 2 , False ),
    ('Budh' ,1, 3 , False ),
    ('Budh' ,2, 4 , False ),
    ('Budh' ,2, 5 , False ),
    ('Budh' ,2, 6 , False ),
    ('Budh' ,3, 7 , False ),
    ('Budh' ,3, 8 , False ),
    ('Budh' ,3, 9 , False ),
    ('Budh' ,4, 10 , False ),
    ('Budh' ,4, 11, False ),
    ('Budh' ,4, 12 , False ),
    ('Budh',5, 13 , False ),
    ('Budh' ,5, 14 , False ),
    ('Budh' ,5, 15 , False );
create Table Wing(
    S_ID int not null,
    S_ID1 int not null,
    S_ID2 int not null,
    S_ID3 int not null,
    S_ID4 int not null,
    S_ID5 int not null,
    Preference Char(20) not null,
    primary key(S_ID)
    );
create table Allotment(
    S_ID int not null,
    H_NAME CHAR(20) not null,
    ROOM_NUMBER int not null,
    primary key(S_ID)
    );
select * from Wing order by Preference ASC;